// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeivHXrr83u5FRROq_WhYHsgC7TnvpsJQ',
    appId: '1:573103440428:web:2da92f413a3c3299cbc789',
    messagingSenderId: '573103440428',
    projectId: 'sample-69db8',
    authDomain: 'sample-69db8.firebaseapp.com',
    storageBucket: 'sample-69db8.appspot.com',
    measurementId: 'G-HXZJW90S00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuixjY9TjHfUialByZ-d7kcgLXWQxQdU',
    appId: '1:573103440428:android:d23c7c0a2df480f9cbc789',
    messagingSenderId: '573103440428',
    projectId: 'sample-69db8',
    storageBucket: 'sample-69db8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZtJ6sNTKwYUpqGb5_U1URIKFoGnmAUfk',
    appId: '1:573103440428:ios:e72a980a5b706883cbc789',
    messagingSenderId: '573103440428',
    projectId: 'sample-69db8',
    storageBucket: 'sample-69db8.appspot.com',
    androidClientId: '573103440428-ah4o7qkc99ddv2aggkpf73h1ur8hlske.apps.googleusercontent.com',
    iosClientId: '573103440428-4b1ghe7vqndaoa5chc7nfrrm74e77j62.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZtJ6sNTKwYUpqGb5_U1URIKFoGnmAUfk',
    appId: '1:573103440428:ios:8d9f828ec9d81487cbc789',
    messagingSenderId: '573103440428',
    projectId: 'sample-69db8',
    storageBucket: 'sample-69db8.appspot.com',
    androidClientId: '573103440428-ah4o7qkc99ddv2aggkpf73h1ur8hlske.apps.googleusercontent.com',
    iosClientId: '573103440428-s83k8cqsr3j60r6mdg6pri2me67ph0bn.apps.googleusercontent.com',
    iosBundleId: 'com.example.sample.RunnerTests',
  );
}
